
#ifndef __MKTDATA_H__
#define __MKTDATA_H__

#include "mktdata/AdminHeartbeat12.h"
#include "mktdata/AdminLogin15.h"
#include "mktdata/AdminLogout16.h"
#include "mktdata/AggressorSide.h"
#include "mktdata/ChannelReset4.h"
#include "mktdata/DecimalQty.h"
#include "mktdata/EventType.h"
#include "mktdata/FLOAT.h"
#include "mktdata/GroupSize8Byte.h"
#include "mktdata/GroupSize.h"
#include "mktdata/HaltReason.h"
#include "mktdata/InstAttribValue.h"
#include "mktdata/LegSide.h"
#include "mktdata/MatchEventIndicator.h"
#include "mktdata/MaturityMonthYear.h"
#include "mktdata/MDEntryTypeBook.h"
#include "mktdata/MDEntryTypeDailyStatistics.h"
#include "mktdata/MDEntryType.h"
#include "mktdata/MDEntryTypeStatistics.h"
#include "mktdata/MDIncrementalRefreshBook32.h"
#include "mktdata/MDIncrementalRefreshDailyStatistics33.h"
#include "mktdata/MDIncrementalRefreshLimitsBanding34.h"
#include "mktdata/MDIncrementalRefreshOrderBook43.h"
#include "mktdata/MDIncrementalRefreshSessionStatistics35.h"
#include "mktdata/MDIncrementalRefreshTrade36.h"
#include "mktdata/MDIncrementalRefreshTradeSummary42.h"
#include "mktdata/MDIncrementalRefreshVolume37.h"
#include "mktdata/MDInstrumentDefinitionFuture27.h"
#include "mktdata/MDInstrumentDefinitionOption41.h"
#include "mktdata/MDInstrumentDefinitionSpread29.h"
#include "mktdata/MDUpdateAction.h"
#include "mktdata/MessageHeader.h"
#include "mktdata/OpenCloseSettlFlag.h"
#include "mktdata/OrderUpdateAction.h"
#include "mktdata/PRICE.h"
#include "mktdata/PRICENULL.h"
#include "mktdata/PutOrCall.h"
#include "mktdata/QuoteRequest39.h"
#include "mktdata/SecurityStatus30.h"
#include "mktdata/SecurityTradingEvent.h"
#include "mktdata/SecurityTradingStatus.h"
#include "mktdata/SecurityUpdateAction.h"
#include "mktdata/SettlPriceType.h"
#include "mktdata/SnapshotFullRefresh38.h"
#include "mktdata/SnapshotFullRefreshOrderBook44.h"
           
#endif // __MKTDATA_H__    



